
SELECT   A.ID ID,
         DESPESA DESPESA,
         DATA DATA,
         VALOR VALOR,
         TIPO TIPO,
         APROVA APROVA,
         NOME NaME,
         CODIGO CODIGO,
         odf_object_code OBJETO,
         PROJETO PROJETO,
		 NUMTIPO NUMTIPO,
		 AREANEGOCIOS AREANEGOCIOS


	FROM(
	SELECT 
	 D.ID IDDESPESA, DES.NOME DESPESA, D.DATADESPESA DATA,INVID IDPROJETO, R.id ID_R,
	 D.INTERAVALOR VALOR,  DES.NOME TIPO, DES.TIPO NUMTIPO,
	 D.INTERAAPROVA APROVA,(R.FIRST_NAME+'  '+R.LAST_NAME) NOME,
	 R.id IDRECURSO,D.CODPROJETO CODIGO, CAST(D.INVID AS VARCHAR)+CAST(D.ID AS VARCHAR)+ CAST(R.ID AS VARCHAR)+CAST(DES.TIPO AS VARCHAR)+CAST(DES.IDDESPESA AS VARCHAR)+CAST(DES.PK AS VARCHAR) ID, D.NAME PROJETO,odf_object_code odf_object_code,
	 AREA.NAME AREANEGOCIOS

	 FROM 

		(SELECT
		(CASE WHEN A.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN C.ID IS NULL THEN (INV.ID) ELSE (C.ID) END) ELSE (B.ID) END) ELSE (D.ID) END) ID,
		INV.ID INVID,
		COD.CODIGO CODPROJETO,
		INV.odf_object_codE odf_object_code,
		INV.NAME NAME,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN 0 ELSE (D.INTERAVALOR) END) ELSE B.IASVALOR  END) ELSE C.IASVALOR END) INTERAVALOR,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN NULL ELSE (D.DATADESPESA) END) ELSE  B.IASDATADESPESA END) ELSE C.IASDATADESPESA END) DATADESPESA,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN NULL ELSE (D.INTERARECURSO) END) ELSE B.IASRECURSO END) ELSE C.IASRECURSO END) INTERARECURSO,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN NULL ELSE (D.ODF_PARENT_ID) END) ELSE B.ODF_PARENT_ID END) ELSE C.ODF_PARENT_ID END) ODF_PARENT_ID,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN NULL ELSE (D.INTERATIPODESPESA) END) ELSE B.IASTIPODESPESA END) ELSE C.IASTIPODESPESA END) INTERATIPODESPESA,
		(CASE WHEN C.ID IS NULL THEN (CASE WHEN B.ID IS NULL THEN( CASE WHEN A.ID IS NULL THEN NULL ELSE (D.INTERAAPROVA) END) ELSE B.APROVADA END) ELSE C.IASAPROVADA END) INTERAAPROVA,
		(CASE WHEN IDEA.AREANEGOCIO IS NULL THEN (CASE WHEN A.AREANEGOCIOS IS NULL THEN NULL ELSE A.AREANEGOCIOS END) ELSE IDEA.AREANEGOCIO END) AREANEGOCIOS
		   FROM INV_INVESTMENTS INV
		LEFT JOIN ODF_CA_IDEA IDEA ON INV.ID = IDEA.ID
		LEFT JOIN ODF_CA_PROJECT A ON INV.ID = A.ID
		LEFT JOIN odf_ca_iasdespesasowork B ON INV.ID = B.ODF_CNCRT_PARENT_ID
		LEFT JOIN ODF_CA_iasdespesasopt C ON INV.ID = C.ODF_CNCRT_PARENT_ID
		LEFT JOIN ODF_CA_INTERDESPESAS D ON INV.ID = D.ODF_CNCRT_PARENT_ID
		LEFT JOIN (
			select inv.id id ,
			CASE WHEN INV.ODF_OBJECT_CODE ='PROJECT' THEN (project.CODPROJETO) WHEN INV.ODF_OBJECT_CODE = 'IDEA' THEN IDEA.oportunitycode ELSE' ' END CODIGO 
			from inv_investments inv 
			left join odf_ca_idea idea on inv.id = idea.id 
			left join odf_ca_project  project on inv.id = project.id
			where inv.IS_ACTIVE = 1
		)cod on inv.id = cod.id
		 WHERE INV.IS_ACTIVE = 1) D
		 
	 INNER JOIN (SELECT  N.NAME NAME, LOOKUP_CODE
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='AREANEGOCIO'
		AND N.CREATED_BY<>'1'
	 )AREA ON AREA.LOOKUP_CODE = AREANEGOCIOS
	 
	 INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
	 INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME, N.ID IDDESPESA, N.PK_ID PK
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
) A