--==QUERY CUSTO PROJETOS DETALHES==--
----19/03 final----

SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@,
 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPOCUSTO@,
 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CUSTO:CUSTO@

FROM(SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID, TIPO, CUSTO

FROM
(SELECT 
CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
CASE WHEN (SL.TIPO) IS NULL THEN EFE.TIPO ELSE (SL.TIPO)END TIPO, 
LP.CUSTO CUSTO, 
CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
FROM

(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
AND SL.SLICE_DATE BETWEEN @WHERE:PARAM:USER_DEF:DATE:pBeginDate@ AND @WHERE:PARAM:USER_DEF:DATE:pEndDate@

) SL

FULL OUTER JOIN 


(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
AND SL.SLICE_DATE BETWEEN @WHERE:PARAM:USER_DEF:DATE:pBeginDate@ AND @WHERE:PARAM:USER_DEF:DATE:pEndDate@
) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES
INNER JOIN 
(SELECT N.NAME CUSTO, C.LOOKUP_CODE INDICE
FROM CMN_LIST_OF_VALUES A
INNER JOIN CMN_LOOKUP_TYPES B ON A.LOOKUP_TYPE_CODE=B.LOOKUP_TYPE
INNER JOIN CMN_LOOKUPS C ON B.LOOKUP_TYPE = C.LOOKUP_TYPE
INNER JOIN CMN_CAPTIONS_NLS N ON C.ID = N.PK_ID
WHERE A.ID=5000307 
AND N.LANGUAGE_CODE = 'en'
AND N.CREATED_BY <> 1
)LP
ON EFE.TIPO = LP.INDICE OR SL.TIPO = LP.INDICE) A
)final


WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@




--==QUERY CUSTO PROJETOS DETALHES==--
----11/02 final(alterada)----

SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:MES:MESLANCAMENTO@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPOCUSTO@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CUSTO:CUSTO@

FROM(
	SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID, MES, TIPO, CUSTO

	FROM
		(SELECT 
		CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
		CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
		CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
		CASE WHEN (SL.MES) IS NULL THEN EFE.MES ELSE (SL.MES)END MES, 
		CASE WHEN (SL.TIPO) IS NULL THEN EFE.TIPO ELSE (SL.TIPO)END TIPO, 
		LP.CUSTO CUSTO, 
		CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
		CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
		CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
		CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
		FROM

			(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
			FROM
			NIKU.ODF_CA_CONTROLEFINAN CON
			INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
			INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
			LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
			WHERE INV.IS_ACTIVE = 1
			) SL

		FULL OUTER JOIN 


				(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
				FROM
				NIKU.ODF_CA_CONTROLEFINAN CON
				INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
				INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
				LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
				WHERE INV.IS_ACTIVE = 1
			) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES
		INNER JOIN 
			(SELECT N.NAME CUSTO, C.LOOKUP_CODE INDICE
			FROM CMN_LIST_OF_VALUES A
			INNER JOIN CMN_LOOKUP_TYPES B ON A.LOOKUP_TYPE_CODE=B.LOOKUP_TYPE
			INNER JOIN CMN_LOOKUPS C ON B.LOOKUP_TYPE = C.LOOKUP_TYPE
			INNER JOIN CMN_CAPTIONS_NLS N ON C.ID = N.PK_ID
			WHERE A.ID=5000307 
			AND N.LANGUAGE_CODE = 'en'
			AND N.CREATED_BY <> 1
			)LP
	ON EFE.TIPO = LP.INDICE OR SL.TIPO = LP.INDICE) A

)final


WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@



--==QUERY CUSTO PROJETOS DETALHES==--
----11/02 12:41----

SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:MES:MESLANCAMENTO@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPOCUSTO@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CUSTO:CUSTO@

FROM(
	SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID, MES, TIPO, CUSTO

	FROM
		(SELECT 
		CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
		CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
		CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
		CASE WHEN (SL.MES) IS NULL THEN EFE.MES ELSE (SL.MES)END MES, 
		CASE WHEN (SL.TIPO) IS NULL THEN EFE.TIPO ELSE (SL.TIPO)END TIPO, 
		LP.CUSTO CUSTO, 
		CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
		CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
		CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
		CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
		FROM

			(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
			FROM
			NIKU.ODF_CA_CONTROLEFINAN CON
			INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
			INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
			LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
			WHERE INV.IS_ACTIVE = 1
			) SL

		FULL OUTER JOIN 


				(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
				FROM
				NIKU.ODF_CA_CONTROLEFINAN CON
				INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
				INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
				LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
				WHERE INV.IS_ACTIVE = 1
			) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES
		INNER JOIN 
			(SELECT N.NAME CUSTO, C.LOOKUP_CODE INDICE
			FROM CMN_LIST_OF_VALUES A
			INNER JOIN CMN_LOOKUP_TYPES B ON A.LOOKUP_TYPE_CODE=B.LOOKUP_TYPE
			INNER JOIN CMN_LOOKUPS C ON B.LOOKUP_TYPE = C.LOOKUP_TYPE
			INNER JOIN CMN_CAPTIONS_NLS N ON C.ID = N.PK_ID
			WHERE A.ID=5000307 
			AND N.LANGUAGE_CODE = 'en'
			AND N.CREATED_BY <> 1
			)LP
	ON EFE.TIPO = LP.INDICE OR SL.TIPO = LP.INDICE) A

)final


WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@




--==QUERY CUSTO DE PROJETO DETALHES==--
------==FINAL==-------

SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:MES:MESLANCAMENTO@,
		 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPOCUSTO@

FROM(SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID, MES, TIPO

FROM
(SELECT 
CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
CASE WHEN (SL.MES) IS NULL THEN EFE.MES ELSE (SL.MES)END MES, 
CASE WHEN (SL.TIPO) IS NULL THEN EFE.MES ELSE (SL.TIPO)END TIPO, 
CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
FROM

(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) SL

FULL OUTER JOIN 


(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES) A
) final



WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@






--==QUERY CUSTO DE PROJETO DETALHES==--
------==09/02/2009==-------


SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@,
	 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPOCUSTO@

FROM(SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID, TIPO

FROM
(SELECT 
CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO,
CASE WHEN (SL.TIPO) IS NULL THEN EFE.TIPO ELSE (SL.TIPO)END TIPO,
CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
FROM

(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) SL

FULL OUTER JOIN 


(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES, CON.TIPOCUSTO TIPO
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES) A
) final



WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@


----------------------------------------------------------------------------------------------------------------------------------------------

--==QUERY CUSTO DE PROJETO DETALHES==--
------==09/02/2009 15:29==-------


SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@

FROM(SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID

FROM
(SELECT 
CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
FROM

(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) MES
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) SL

FULL OUTER JOIN 


(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) MES
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES= EFE.MES) A
) final



WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@



-----------------------------------------------------------------------------------------------------------------------------------------------------------

--==QUERY CUSTO DE PROJETO DETALHES==--
------==09/02/2009 12:27==-------

SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:(ID+saldo):ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:Codigo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:Projeto@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PLANEJADO:Planejado@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:EFETIVO:Efetivo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:saldo:Saldo@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:INVID:PROJETOID@

FROM(SELECT CODIGO, PROJETO,PLANEJADO PLANEJADO, EFETIVO EFETIVO,PLANEJADO-EFETIVO Saldo, PRJ_PLAN+PRJ_EFE ID,INVID

FROM
(SELECT 
CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END PLANEJADO, 
CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END EFETIVO,
CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END PRJ_PLAN,
CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END PRJ_EFE
FROM

(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID INV_ID
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) SL

FULL OUTER JOIN 


(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SL.SLICE SLICE, SL.PRJ_OBJECT_ID PRJ_OBJECT_ID, INV.ID EFE_INVID
FROM
NIKU.ODF_CA_CONTROLEFINAN CON
INNER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
INNER JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
WHERE INV.IS_ACTIVE = 1
) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID) A
) final



WHERE @FILTER@
AND INVID=@where:param:xml:integer:/data/idProjeto/@value@