SELECT NOME, ISNULL(ESTACIONAMENTO,0),ISNULL(PEDAGIO,0),ISNULL(ALMOCO,0),ISNULL(TRANSPORTE,0),ISNULL(HAPPYHOUR,0),ISNULL(TAXI,0),(ISNULL(ESTACIONAMENTO,0)+ISNULL(PEDAGIO,0)+ISNULL(ALMOCO,0)+ISNULL(TRANSPORTE,0)+ISNULL(HAPPYHOUR,0)+ISNULL(TAXI,0)) REEMBOLSO
FROM(

		SELECT 
		CASE WHEN (ESTACIONAMENTO.NOME) IS NULL THEN (CASE WHEN (PEDAGIO.NOME) IS NULL THEN (CASE WHEN (ALMOCO.NOME) IS NULL THEN (CASE WHEN (TRANSPORTE.NOME) IS NULL THEN (CASE WHEN (HH.NOME) IS NULL THEN (CASE WHEN (TAXI.NOME) IS NULL THEN ' ' ELSE (TAXI.NOME)end) ELSE (HH.NOME)end) ELSE (TRANSPORTE.NOME)end) ELSE (ALMOCO.NOME)end) ELSE (PEDAGIO.NOME)end) ELSE (ESTACIONAMENTO.NOME) END NOME,
		SUM(ESTACIONAMENTO.VALORESTAC) ESTACIONAMENTO, SUM(PEDAGIO.VALORPEDAGIO) PEDAGIO, SUM(ALMOCO.VALORALMOCO) ALMOCO, SUM(TRANSPORTE.VALORTRANS) TRANSPORTE,
		SUM(HH.VALORHH) HAPPYHOUR, SUM(TAXI.VALORTAXI) TAXI
--CASE WHEN (ESTACIONAMENTO.DATE) IS NULL THEN (CASE WHEN (PEDAGIO.DATE) IS NULL THEN (CASE WHEN (ALMOCO.DATE) IS NULL THEN (CASE WHEN (TRANSPORTE.DATE) IS NULL THEN (CASE WHEN (HH.DATE) IS NULL THEN (CASE WHEN (TAXI.DATE) IS NULL THEN NULL ELSE (TAXI.DATE)end) ELSE (HH.DATE)end) ELSE (TRANSPORTE.DATE)end) ELSE (ALMOCO.DATE)end) ELSE (PEDAGIO.DATE)end) ELSE (ESTACIONAMENTO.DATE) END DATE



		FROM(
			SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORESTAC, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 1)ESTACIONAMENTO

		FULL OUTER JOIN 

			(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORPEDAGIO, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 2)PEDAGIO 

		ON PEDAGIO.IDUSER = ESTACIONAMENTO.IDUSER

		FULL OUTER JOIN

		(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORALMOCO, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 3)ALMOCO 

		ON PEDAGIO.IDUSER = ALMOCO.IDUSER

		FULL OUTER JOIN
		(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORTRANS, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 14)TRANSPORTE 

		ON ALMOCO.IDUSER = TRANSPORTE.IDUSER

		FULL OUTER JOIN
		(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORHH, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 5)HH 

		ON TRANSPORTE.IDUSER = HH.IDUSER

		FULL OUTER JOIN
		(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORTAXI, R.ID IDUSER, DES.DATE
			FROM
				ODF_CA_INTERDESPESAS D
				INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
				INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
				INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
				INNER JOIN
				(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME,N.CREATED_DATE DATE
				FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
				WHERE L.ID = N.PK_ID
				AND N.LANGUAGE_CODE = 'en'
				AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
				AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
			WHERE DES.TIPO = 6)TAXI

		ON HH.IDUSER = TAXI.IDUSER



		GROUP BY ESTACIONAMENTO.NOME, PEDAGIO.NOME, ALMOCO.NOME, TRANSPORTE.NOME, HH.NOME, TAXI.NOME--, ESTACIONAMENTO.DATE, PEDAGIO.DATE, ALMOCO.DATE, TRANSPORTE.DATE, HH.DATE, TAXI.DATE
)A


-----------------



SELECT 
CASE WHEN (ESTACIONAMENTO.NOME) IS NULL THEN (CASE WHEN (PEDAGIO.NOME) IS NULL THEN (CASE WHEN (ALMOCO.NOME) IS NULL THEN (CASE WHEN (TRANSPORTE.NOME) IS NULL THEN (CASE WHEN (HH.NOME) IS NULL THEN ' ' ELSE (HH.NOME)end) ELSE (TRANSPORTE.NOME)end) ELSE (ALMOCO.NOME)end) ELSE (PEDAGIO.NOME)end) ELSE (ESTACIONAMENTO.NOME) END CODIGO,
SUM(ESTACIONAMENTO.VALORESTAC) ESTACIONAMENTO, SUM(PEDAGIO.VALORPEDAGIO) PEDAGIO, SUM(ALMOCO.VALORALMOCO) ALMOCO, SUM(TRANSPORTE.VALORTRANS) TRANSPORTE,
SUM(HH.VALORHH) HAPPYHOUR



FROM(
	SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORESTAC, R.ID IDUSER
	FROM
		ODF_CA_INTERDESPESAS D
		INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
		INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
		INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
		INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
	WHERE DES.TIPO = 1)ESTACIONAMENTO

FULL OUTER JOIN 

	(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORPEDAGIO, R.ID IDUSER
	FROM
		ODF_CA_INTERDESPESAS D
		INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
		INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
		INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
		INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
	WHERE DES.TIPO = 2)PEDAGIO 

ON PEDAGIO.IDUSER = ESTACIONAMENTO.IDUSER

FULL OUTER JOIN

(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORALMOCO, R.ID IDUSER
	FROM
		ODF_CA_INTERDESPESAS D
		INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
		INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
		INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
		INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
	WHERE DES.TIPO = 3)ALMOCO 

ON PEDAGIO.IDUSER = ALMOCO.IDUSER

FULL OUTER JOIN
(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORTRANS, R.ID IDUSER
	FROM
		ODF_CA_INTERDESPESAS D
		INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
		INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
		INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
		INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
	WHERE DES.TIPO = 14)TRANSPORTE 

ON ALMOCO.IDUSER = TRANSPORTE.IDUSER

FULL OUTER JOIN
(SELECT (R.FIRST_NAME+'  '+R.LAST_NAME) NOME, D.INTERAVALOR VALORHH, R.ID IDUSER
	FROM
		ODF_CA_INTERDESPESAS D
		INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
		INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
		INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
		INNER JOIN
		(SELECT L.LOOKUP_CODE TIPO, N.NAME NOME
		FROM CMN_LOOKUPS L, CMN_CAPTIONS_NLS N
		WHERE L.ID = N.PK_ID
		AND N.LANGUAGE_CODE = 'en'
		AND L.LOOKUP_TYPE='INTERATIPODESPESAS'
		AND N.CREATED_BY<>'1')DES ON DES.TIPO=D.INTERATIPODESPESA
	WHERE DES.TIPO = 5)HH 

ON TRANSPORTE.IDUSER = HH.IDUSER



GROUP BY ESTACIONAMENTO.NOME, PEDAGIO.NOME, ALMOCO.NOME, TRANSPORTE.NOME, HH.NOME


