--QUERY SQL/SERVER--
--==FATURAMENTOS FUTUROS MILESTONE==--

SELECT   ID ID,
         PROJETO PROJETO,
 CODIGO CODIGO,
 TAREFA TAREFA,
 VALORPAG VALOR,
 DATAFAT DATAAFATURAR,
 DATARECEBIMENTO DATADOFATURAMENTO,
 (CAST(DATARECEBIMENTO AS NUMERIC))-(CAST(GETDATE() AS NUMERIC)) DIASAFATURAR



FROM     
(SELECT INV.NAME PROJETO, INV.CODE CODIGO, T.PRNAME TAREFA, A.VALORPAG VALORPAG, A.DATAFAT DATAFAT, A.DATARECEBIMENTO DATARECEBIMENTO ,T.PRID ID, GETDATE() HOJE
FROM INV_INVESTMENTS INV 
INNER JOIN PRTASK T
 ON T.PRPROJECTID = INV.ID
 INNER JOIN ODF_CA_TASK A
 ON T.PRID = A.ID
 WHERE PRISMILESTONE = 1 
 AND A.DATAFAT>=GETDATE()
 AND A.DATAFAT<=(DATEADD(DAY,10,GETDATE()))
) RES

WHERE    1=1