SELECT   @SELECT:DIM:USER_DEF:IMPLIED:RESOURCE:ID:ID@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:DESPESA:DESPESA@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:DATAA:DATA@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:VALOR:VALOR@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:TIPO:TIPO@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:APROVA:APROVA@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:NOME:NOME@,
         @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:CODIGO:CODIGO@,
 @SELECT:DIM_PROP:USER_DEF:IMPLIED:RESOURCE:PROJETO:PROJETO@

FROM(
SELECT 
         D.NAME DESPESA, D.DATADESPESA DATAA,
         D.INTERAVALOR VALOR, D.INTERATIPODESPESA TIPO,
         D.INTERAAPROVA APROVA,(R.FIRST_NAME+'  '+R.LAST_NAME) NOME,
         R.id IDRECURSO,P.CODPROJETO CODIGO, P.ID+D.ID+R.ID ID, INV.NAME PROJETO, INV.ID IDPROJETO

         FROM ODF_CA_INTERDESPESAS D
         INNER JOIN SRM_RESOURCES R ON D.INTERARECURSO=R.ID
         INNER JOIN ODF_CA_PROJECT P ON D.ODF_PARENT_ID = P.ID
 INNER JOIN INV_INVESTMENTS INV ON P.ID = INV.ID
 WHERE INV.IS_ACTIVE=1) A
 


WHERE    @FILTER@
AND   ((IDRECURSO IS NULL) OR (@WHERE:PARAM:USER_DEF:INTEGER:IDRECURSO:Recurso@))
AND   ((IDPROJETO IS NULL) OR (@WHERE:PARAM:USER_DEF:INTEGER:IDPROJETO:Projeto@))