SELECT   ID ID,
         CODIGO Codigo,
         PROJETO Projeto,
         PLANEJADO Planejado,
         EFETIVO Efetivo,
         saldo Saldo,
         INVID PROJETOID,
         GERENTE GERENTE,
         MANAGERID IDGERENTE,
         @param_pbegindate dateend
		 @param_pbegindate

	FROM(SELECT CODIGO, PROJETO, SUM(PLANEJADO) PLANEJADO, SUM(EFETIVO) EFETIVO,SUM(PLANEJADO-EFETIVO) Saldo, SUM(PRJ_PLAN+PRJ_EFE+PLANEJADO+INVID) ID, INVID, GERENTE, MANAGERID

	FROM
		(SELECT 
		CASE WHEN (INV_ID) IS NULL THEN EFE_INVID ELSE (INV_ID) END INVID,
		CASE WHEN (SL.CODE) IS NULL THEN EFE.CODE ELSE (SL.CODE)END CODIGO, 
		CASE WHEN (SL.NAME) IS NULL THEN EFE.NAME ELSE (SL.NAME)END PROJETO, 
		SUM(CASE WHEN (SL.SLICE) IS NULL THEN 0 ELSE (SL.SLICE) END) PLANEJADO, 
		SUM(CASE WHEN (EFE.SLICE) IS NULL THEN 0 ELSE (EFE.SLICE) END) EFETIVO,
		SUM(CASE WHEN (SL.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (SL.PRJ_OBJECT_ID)END) PRJ_PLAN,
		SUM(CASE WHEN (EFE.PRJ_OBJECT_ID) IS NULL THEN 0 ELSE (EFE.PRJ_OBJECT_ID)END) PRJ_EFE,
		CASE WHEN (SL.GERENTE) IS NULL THEN EFE.GERENTE ELSE (SL.GERENTE)END GERENTE,
		CASE WHEN (SL.MANAGERID) IS NULL THEN EFE.MANAGERID ELSE (SL.MANAGERID) END MANAGERID
		FROM

		(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SUM(SL.SLICE) SLICE, SUM(SL.PRJ_OBJECT_ID) PRJ_OBJECT_ID, INV.ID INV_ID, MONTH(SL.SLICE_DATE) Mes, (SRM.FIRST_NAME +' '+SRM.LAST_NAME) GERENTE, SRM.USER_ID MANAGERID
		FROM
		NIKU.ODF_CA_CONTROLEFINAN CON
		FULL OUTER JOIN NIKU.ODF_SL_5025018 SL ON CON.ID = SL.PRJ_OBJECT_ID
		RIGHT JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
		LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
		LEFT JOIN CMN_SEC_USERS USERS ON USERS.ID=INV.MANAGER_ID
		LEFT JOIN SRM_RESOURCES SRM ON  USERS.ID=SRM.USER_ID
		WHERE INV.IS_ACTIVE = 1
		AND SL.SLICE_DATE BETWEEN @WHERE:PARAM:USER_DEF:DATE:pBeginDate@ AND @WHERE:PARAM:USER_DEF:DATE:pEndDate@
		AND INV.ODF_OBJECT_CODE = 'PROJECT'
		GROUP BY ca.CODPROJETO, INV.NAME,INV.ID, SL.SLICE_DATE, SRM.FIRST_NAME, SRM.LAST_NAME, SRM.USER_ID
		) SL

	FULL OUTER JOIN 


		(SELECT ca.CODPROJETO CODE, INV.NAME NAME, SUM(SL.SLICE) SLICE, SUM(SL.PRJ_OBJECT_ID) PRJ_OBJECT_ID, INV.ID EFE_INVID, MONTH(SL.SLICE_DATE) Mes, (SRM.FIRST_NAME +' '+SRM.LAST_NAME) GERENTE, SRM.USER_ID MANAGERID
		FROM
		NIKU.ODF_CA_CONTROLEFINAN CON
		FULL OUTER JOIN NIKU.ODF_SL_5025020 SL ON CON.ID = SL.PRJ_OBJECT_ID
		RIGHT JOIN NIKU.INV_INVESTMENTS INV ON CON.ODF_CNCRT_PARENT_ID = INV.ID
		LEFT JOIN NIKU.ODF_CA_PROJECT AS CA ON INV.ID = CA.ID
		LEFT JOIN CMN_SEC_USERS USERS ON USERS.ID=INV.MANAGER_ID
		LEFT JOIN SRM_RESOURCES SRM ON  USERS.ID=SRM.USER_ID
		WHERE INV.IS_ACTIVE = 1
		AND INV.ODF_OBJECT_CODE = 'PROJECT'
		AND SL.SLICE_DATE BETWEEN @WHERE:PARAM:USER_DEF:DATE:pBeginDate@ AND @WHERE:PARAM:USER_DEF:DATE:pEndDate@

		GROUP BY ca.CODPROJETO, INV.NAME, INV.ID, SL.SLICE_DATE, SRM.FIRST_NAME, SRM.LAST_NAME, SRM.USER_ID

		) EFE ON SL.PRJ_OBJECT_ID = EFE.PRJ_OBJECT_ID AND SL.MES = EFE.MES

	GROUP BY SL.CODE, SL.NAME, EFE.NAME, EFE.CODE,INV_ID, EFE_INVID, SL.MANAGERID, SL.GERENTE, EFE.MANAGERID, EFE.GERENTE) A

	GROUP BY CODIGO, A.PROJETO, INVID, MANAGERID, GERENTE


) final




WHERE ((MANAGERID IS NULL) OR (@WHERE:PARAM:USER_DEF:INTEGER:MANAGERID:MANAGERID@))
AND @FILTER@  